$ANSIBLE_VAULT;1.1;AES256
36653262373439376335353962626162653830663630336135333965323962663636643335346632
3064396535333766663865633135383766376638303362380a636633646232646332643262333338
65326336393366356266376163343738313764633636323832383431663938653063623331653634
3963343665343737650a326536396136643736336531393634393132376634303461316332333830
6636
